'''
--- Day 7: Laboratories ---
You thank the cephalopods for the help and exit the trash compactor, finding yourself in the familiar halls of a North Pole research wing.

Based on the large sign that says "teleporter hub", they seem to be researching teleportation; you can't help but try it for yourself and step onto the large yellow teleporter pad.

Suddenly, you find yourself in an unfamiliar room! The room has no doors; the only way out is the teleporter. Unfortunately, the teleporter seems to be leaking magic smoke.

Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment lying around. After connecting one of the diagnostic tools, it helpfully displays error code 0H-N0, which apparently means that there's an issue with one of the tachyon manifolds.

You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters the manifold at the location marked S; tachyon beams always move downward. Tachyon beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.

For example:

.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:

.......S.......
.......|.......
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
At that point, the original beam stops, and two new beams are emitted from the splitter:

.......S.......
.......|.......
......|^|......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
Those beams continue downward until they reach more splitters:

.......S.......
.......|.......
......|^|......
......|.|......
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
At this point, the two splitters create a total of only three tachyon beams, since they are both dumping tachyons into the same place between them:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
This process continues until all of the tachyon beams reach a splitter or exit the manifold:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
.....|.|.|.....
....|^|^|^|....
....|.|.|.|....
...|^|^|||^|...
...|.|.|||.|...
..|^|^|||^|^|..
..|.|.|||.|.|..
.|^|||^||.||^|.
.|.|||.||.||.|.
|^|^|^|^|^|||^|
|.|.|.|.|.|||.|
To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of 21 times.

Analyze your manifold diagram. How many times will the beam be split?
'''

sample_data = [
  '.......S.......',
  '...............',
  '.......^.......',
  '...............',
  '......^.^......',
  '...............',
  '.....^.^.^.....',
  '...............',
  '....^.^...^....',
  '...............',
  '...^.^...^.^...',
  '...............',
  '..^...^.....^..',
  '...............',
  '.^.^.^.^.^...^.',
  '...............'
]

from collections import deque

def part1(diagram: list[str]) -> int:
  '''
  Returns number of times the tachyon beam gets splitted starting from S moving downward
  Can assume the are no adjacent splitters
  
  :param diagram: a diagram of the tachyon manifold
  :type diagram: list[str]
  :return: number of times the beam gets splitted
  :rtype: int
  '''

  m, n = len(diagram), len(diagram[0])

  start_x, start_y = None, None
  
  for i in range(m):
    for j in range(n):
      if diagram[i][j] == 'S':
        start_x, start_y = i, j
        break
    
    if start_x is not None:
      break

  queue = deque([(start_x, start_y)])
  visited = [[False] * n for _ in range(m)]
  visited[start_x][start_y] = True

  cnt = 0

  while queue:
    x, y = queue.popleft()

    if x == m - 1:
      continue

    if visited[x + 1][y]:
      continue

    if diagram[x + 1][y] == '.':
      queue.append((x + 1, y))
      visited[x + 1][y] = True
    else:
      cnt += 1

      if y > 0 and not visited[x + 1][y - 1]:
        visited[x + 1][y - 1] = True
        queue.append((x + 1, y - 1))

      if y + 1 < n and not visited[x + 1][y + 1]:
        visited[x + 1][y + 1] = True
        queue.append((x + 1, y + 1))

  return cnt

import os

data = []
with open(os.path.join(os.path.dirname(__file__), 'input.txt'), 'r') as file:
  for line in file.readlines():
    data.append(line.strip())

# print(part1(data))

'''
--- Part Two ---
With your analysis of the manifold complete, you begin fixing the teleporter. However, as you open the side of the teleporter to replace the broken manifold, you are surprised to discover that it isn't a classical tachyon manifold - it's a quantum tachyon manifold.

With a quantum tachyon manifold, only a single tachyon particle is sent through the manifold. A tachyon particle takes both the left and right path of each splitter encountered.

Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time a particle reaches a splitter, it's actually time itself which splits. In one timeline, the particle went left, and in the other timeline, the particle went right.

To fix the manifold, what you really need to know is the number of timelines active after a single particle completes all of its possible journeys through the manifold.

In the above example, there are many timelines. For instance, there's the timeline where the particle always went left:

.......S.......
.......|.......
......|^.......
......|........
.....|^.^......
.....|.........
....|^.^.^.....
....|..........
...|^.^...^....
...|...........
..|^.^...^.^...
..|............
.|^...^.....^..
.|.............
|^.^.^.^.^...^.
|..............
Or, there's the timeline where the particle alternated going left and right at each splitter:

.......S.......
.......|.......
......|^.......
......|........
......^|^......
.......|.......
.....^|^.^.....
......|........
....^.^|..^....
.......|.......
...^.^.|.^.^...
.......|.......
..^...^|....^..
.......|.......
.^.^.^|^.^...^.
......|........
Or, there's the timeline where the particle ends up at the same point as the alternating timeline, but takes a totally different path to get there:

.......S.......
.......|.......
......|^.......
......|........
.....|^.^......
.....|.........
....|^.^.^.....
....|..........
....^|^...^....
.....|.........
...^.^|..^.^...
......|........
..^..|^.....^..
.....|.........
.^.^.^|^.^...^.
......|........
In this example, in total, the particle ends up on 40 different timelines.

Apply the many-worlds interpretation of quantum tachyon splitting to your manifold diagram. In total, how many different timelines would a single tachyon particle end up on?
'''

from functools import cache

def part2(diagram: list[str]) -> int:
  m, n = len(diagram), len(diagram[0])

  @cache
  def dp(r: int, c: int) -> int:
    '''
    Returns number of possible timeline where the tachyon beam faces a splitter, it can be sent to the left or right.
    Can assume there are no adjacent splitters, and no splitters at the bottom row
    
    :param r: current beam's row
    :type r: int
    :param c: current beam's column
    :type c: int
    :return: number of possible timelines
    :rtype: int
    '''

    if r == m - 1:
      return 1

    # Out of bound
    if c < 0 or c >= n:
      return 0
    
    if diagram[r + 1][c] == '.':
      return dp(r + 1, c)
    
    return dp(r + 1, c - 1) + dp(r + 1, c + 1)


  start_x, start_y = None, None
  for i in range(m):
    for j in range(n):
      if diagram[i][j] == 'S':
        start_x, start_y = i, j
        break

    if start_x is not None:
      break

  return dp(start_x, start_y)

print(
  part2(data)
)
